spring:
  profiles:
    include: "git"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/OpsMx/newdev-dyn-account.git"
          username: "girichinna27"
          password: "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"
encrypt:
  key: "Q7udUkHPuA3VnNlOtksSgQ"
